modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "ae2objects"
version = "${version}"
displayName = "AE2Objects"
logoFile = "icon.png"
credits = "Based on AE2Things by ProjectET and Technici4n."
authors = "Likos-Lupus, ProjectET, Technici4n"
description = '''
This mod adds Deep Item Storage Cells to Applied Energistics 2.
These cells have no type limits and one item counts as one byte.
Due to limitations with the cell format, you lose 24 bytes per kibibyte, but hey a small price to pay for no types right?
'''

[[mixins]]
config = "ae2objects.mixins.json"

[[dependencies.ae2objects]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.71,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2objects]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2, 26.2.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2objects]]
modId = "ae2"
type = "required"
versionRange = "[26.1.10-beta, 26.2.0)"
ordering = "AFTER"
side = "BOTH"
